#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}flake8 webtypes tests
${PREFIX}isort webtypes tests --recursive --check-only
#${PREFIX}mypy webtypes tests --ignore-missing-imports
